/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MerkleProof {
  path: Array<Buffer>
  indices: Array<boolean>
}
export interface NullifierData {
  salt: Buffer
  timestamp: number
}
export interface AmountCommitment {
  commitment: Buffer
  amount: number
  blindingFactor: Buffer
}
export interface SpendNoteInput {
  walletAddress: Buffer
  nullifier: Buffer
  amountCommitment: AmountCommitment
  nullifierData: NullifierData
}
export interface SpendProof {
  receipt: Buffer
  merkleRoot: Buffer
  nullifier: Buffer
  amount: number
}
export declare function verifySpend(proof: SpendProof): Promise<boolean>
export declare class ProofGenerator {
  constructor()
  proveSpend(walletAddress: Buffer, amount: number, merkleProof: MerkleProof, merkleRoot: Buffer): Promise<SpendProof>
}
